version: "3"
#version: "3.9"
#version: "2.3"
# 创建网络
networks:
  redis_cluster_network:
    driver_opts:
      com.docker.network.bridge.name: "custom_bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.16.22.0/24
          gateway: 172.16.22.1
# 创建服务
services:
  redis_6390:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.2
    container_name: redis_6390
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6390:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
  redis_6391:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.3
    container_name: redis_6391
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6391:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6392:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.4
    container_name: redis_6392
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6392:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6393:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.5
    container_name: redis_6393
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6393:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6394:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.6
    container_name: redis_6394
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6394:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6395:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.7
    container_name: redis_6395
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6395:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6396:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.8
    container_name: redis_6396
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6396:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6397:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.9
    container_name: redis_6397
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6397:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6398:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.10
    container_name: redis_6398
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6398:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
  redis_6399:
    networks:
      redis_cluster_network:
        ipv4_address: 172.16.22.11
    container_name: redis_6399
    image: redis:latest
    restart: always
    volumes:
      - /Users/mshe/developer/data:/usr/local/etc/redis
    ports:
      - "6399:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_cluster.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6390
